using System.Collections.ObjectModel;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.Utilities;using MFCYouthAreaManagementSystem.ViewModels.Base;
namespace MFCYouthAreaManagementSystem.ViewModels;
public sealed class DashboardHomeViewModel:ObservableObject
{
 private string _totalMembers="—",_activeMembers="—",_totalChapters="—",_totalServices="—",_totalReports="—",_totalEvents="—",_registrations="—",_attendance="—";
 public string TotalMembers{get=>_totalMembers;set=>SetProperty(ref _totalMembers,value);}public string ActiveMembers{get=>_activeMembers;set=>SetProperty(ref _activeMembers,value);}public string TotalChapters{get=>_totalChapters;set=>SetProperty(ref _totalChapters,value);}public string TotalServices{get=>_totalServices;set=>SetProperty(ref _totalServices,value);}public string TotalReports{get=>_totalReports;set=>SetProperty(ref _totalReports,value);}public string TotalEvents{get=>_totalEvents;set=>SetProperty(ref _totalEvents,value);}public string EventRegistrations{get=>_registrations;set=>SetProperty(ref _registrations,value);}public string RecordedAttendance{get=>_attendance;set=>SetProperty(ref _attendance,value);}
 private string _trendText="";public string TrendText{get=>_trendText;set=>SetProperty(ref _trendText,value);}public ObservableCollection<AreaEvent> UpcomingEvents{get;}=new();public ObservableCollection<AreaEvent> PastEvents{get;}=new();public ObservableCollection<Chapter> ChapterDistribution{get;}=new();
 public DashboardHomeViewModel(){RefreshStats();}
 public void RefreshStats(){try{var members=new MemberRepository();var chapters=new ChapterRepository();var participants=new EventParticipantRepository();var eventsRepo=new EventRepository();TotalMembers=members.GetTotalCount().ToString();ActiveMembers=members.GetActiveCount().ToString();TotalChapters=chapters.GetTotalCount().ToString();TotalServices=new ServiceRepository().GetTotalCount().ToString();TotalReports=new ActivityReportRepository().GetTotalCount().ToString();TotalEvents=eventsRepo.GetTotalCount().ToString();EventRegistrations=participants.GetTotalCount().ToString();RecordedAttendance=participants.GetAttendedCount().ToString();DashboardTrendStore.CaptureCurrentTotals();var now=DateTime.Now;var current=DashboardTrendStore.GetForMonth(now.ToString("yyyy-MM"));var previous=DashboardTrendStore.GetForMonth(now.AddMonths(-1).ToString("yyyy-MM"));TrendText=previous==null?"Monthly trend history will populate as the app is used.":$"Vs. previous month: Members {Delta(current?.Members,previous.Members)}, Reports {Delta(current?.ActivityReports,previous.ActivityReports)}, Events {Delta(current?.Events,previous.Events)}, Registrations {Delta(current?.EventRegistrations,previous.EventRegistrations)}";var allEvents=eventsRepo.GetAll();UpcomingEvents.Clear();foreach(var e in allEvents.Where(x=>x.EventDateTime>=now).OrderBy(x=>x.EventDateTime).Take(5))UpcomingEvents.Add(e);PastEvents.Clear();foreach(var e in allEvents.Where(x=>x.EventDateTime<now).OrderByDescending(x=>x.EventDateTime).Take(5))PastEvents.Add(e);ChapterDistribution.Clear();foreach(var c in chapters.GetAll().OrderByDescending(x=>x.MemberCount).ThenBy(x=>x.ChapterName))ChapterDistribution.Add(c);}catch(Exception ex){AppLogger.Error("Refresh WPF dashboard",ex);TrendText="Dashboard data could not be fully loaded. Check the application log for details.";}}
 private static string Delta(int? current,int? previous){if(!current.HasValue||!previous.HasValue)return "—";var d=current.Value-previous.Value;return d>0?$"+{d}":d.ToString();}
}
