using System.Collections.ObjectModel;using System.Windows;using System.Windows.Input;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.ViewModels.Base;using MFCYouthAreaManagementSystem.Views.Dialogs;
namespace MFCYouthAreaManagementSystem.ViewModels;
public sealed class EventsViewModel:ObservableObject
{
 private readonly EventRepository _repo=new();public ObservableCollection<AreaEvent> Events{get;}=new();private string _search="";public string SearchText{get=>_search;set{if(SetProperty(ref _search,value))Load();}}private AreaEvent? _selected;public AreaEvent? SelectedEvent{get=>_selected;set{if(SetProperty(ref _selected,value))CommandManager.InvalidateRequerySuggested();}}
 public ICommand AddCommand{get;}public ICommand EditCommand{get;}public ICommand DetailsCommand{get;}public ICommand DeleteCommand{get;}public ICommand RefreshCommand{get;}
 public EventsViewModel(){AddCommand=new RelayCommand(Add);EditCommand=new RelayCommand(Edit,Has);DetailsCommand=new RelayCommand(Details,Has);DeleteCommand=new RelayCommand(Delete,Has);RefreshCommand=new RelayCommand(Load);Load();}private bool Has()=>SelectedEvent!=null;private Window? Owner=>Application.Current?.MainWindow;
 public void Load(){try{Events.Clear();foreach(var x in _repo.GetAll(SearchText??""))Events.Add(x);}catch(Exception ex){MessageBox.Show(Owner,ex.Message,"Unable to load events",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Add(){var d=new EventEditorWindow{Owner=Owner};if(d.ShowDialog()==true)Load();}private void Edit(){if(SelectedEvent==null)return;if(new EventEditorWindow(SelectedEvent.EventID){Owner=Owner}.ShowDialog()==true)Load();}private void Details(){if(SelectedEvent==null)return;var d=new EventDetailsWindow(SelectedEvent.EventID){Owner=Owner};d.ShowDialog();if(d.Changed)Load();}
 private void Delete(){if(SelectedEvent==null)return;if(MessageBox.Show(Owner,$"Delete event '{SelectedEvent.EventName}'? Participant registrations will also be deleted, while linked Activity Reports keep the event name snapshot.","Confirm delete",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;try{_repo.Delete(SelectedEvent.EventID);Load();}catch(Exception ex){MessageBox.Show(Owner,ex.Message,"Unable to delete event",MessageBoxButton.OK,MessageBoxImage.Warning);}}
}
