using System.Collections.ObjectModel;using System.Windows;using System.Windows.Input;using Microsoft.Win32;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.Utilities;using MFCYouthAreaManagementSystem.ViewModels.Base;using MFCYouthAreaManagementSystem.Views.Dialogs;
namespace MFCYouthAreaManagementSystem.ViewModels;
public sealed class ReportsViewModel:ObservableObject
{
 private readonly ActivityReportRepository _repo=new();public ObservableCollection<ActivityReport> Reports{get;}=new();public ObservableCollection<ChapterOption> ChapterOptions{get;}=new();public ObservableCollection<string> ReportTypes{get;}=new();public ObservableCollection<AnalyticsItem> MonthlyAnalytics{get;}=new();public ObservableCollection<AnalyticsItem> TypeAnalytics{get;}=new();public ObservableCollection<AnalyticsItem> ChapterAnalytics{get;}=new();
 private string _search="";public string SearchText{get=>_search;set{if(SetProperty(ref _search,value))Load();}}private ChapterOption? _chapter;public ChapterOption? SelectedChapter{get=>_chapter;set{if(SetProperty(ref _chapter,value))Load();}}private string? _type;public string? SelectedReportType{get=>_type;set{if(SetProperty(ref _type,value))Load();}}private DateTime? _from;public DateTime? DateFrom{get=>_from;set{if(SetProperty(ref _from,value))Load();}}private DateTime? _to;public DateTime? DateTo{get=>_to;set{if(SetProperty(ref _to,value))Load();}}private ActivityReport? _selected;public ActivityReport? SelectedReport{get=>_selected;set{if(SetProperty(ref _selected,value))CommandManager.InvalidateRequerySuggested();}}
 private string _summary="";public string Summary{get=>_summary;set=>SetProperty(ref _summary,value);}public ICommand AddCommand{get;}public ICommand EditCommand{get;}public ICommand DeleteCommand{get;}public ICommand ExportCommand{get;}public ICommand ClearFiltersCommand{get;}public ICommand RefreshCommand{get;}
 public ReportsViewModel(){AddCommand=new RelayCommand(Add);EditCommand=new RelayCommand(Edit,()=>SelectedReport!=null);DeleteCommand=new RelayCommand(Delete,()=>SelectedReport!=null);ExportCommand=new RelayCommand(Export,()=>Reports.Count>0);ClearFiltersCommand=new RelayCommand(ClearFilters);RefreshCommand=new RelayCommand(Refresh);LoadFilters();Load();}
 private Window? Owner=>Application.Current?.MainWindow;
 private void LoadFilters(){ChapterOptions.Clear();ChapterOptions.Add(new ChapterOption("All Chapters",null,null));foreach(var c in new ChapterRepository().GetAll())ChapterOptions.Add(new ChapterOption(c.ChapterName,c.ChapterID,null));foreach(var name in _repo.GetHistoricalChapterNames())if(!ChapterOptions.Any(x=>x.ChapterId==null&&string.Equals(x.HistoricalName,name,StringComparison.OrdinalIgnoreCase)))ChapterOptions.Add(new ChapterOption(name+" (Historical)",null,name));_chapter=ChapterOptions.FirstOrDefault();OnPropertyChanged(nameof(SelectedChapter));ReportTypes.Clear();ReportTypes.Add("All Report Types");foreach(var t in ApplicationConstants.ReportTypes)ReportTypes.Add(t);_type="All Report Types";OnPropertyChanged(nameof(SelectedReportType));}
 public void Load(){try{var filter=new ActivityReportFilter{Search=SearchText??"",ChapterID=SelectedChapter?.ChapterId,HistoricalChapterName=SelectedChapter?.HistoricalName,ReportType=SelectedReportType=="All Report Types"?null:SelectedReportType,DateFrom=DateFrom?.Date,DateTo=DateTo?.Date.AddDays(1).AddTicks(-1)};var rows=_repo.GetAll(filter);Reports.Clear();foreach(var r in rows)Reports.Add(r);var chapterCount=rows.Select(x=>x.ChapterName).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Count();var typeCount=rows.Select(x=>x.ReportType).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Count();Summary=$"{rows.Count} report(s) • {chapterCount} chapter(s) • {typeCount} report type(s)";BuildAnalytics(rows);CommandManager.InvalidateRequerySuggested();}catch(Exception ex){MessageBox.Show(Owner,ex.Message,"Unable to load reports",MessageBoxButton.OK,MessageBoxImage.Warning);}}

 private void BuildAnalytics(IReadOnlyList<ActivityReport> rows){MonthlyAnalytics.Clear();var monthStart=new DateTime(DateTime.Today.Year,DateTime.Today.Month,1);var months=Enumerable.Range(0,6).Select(i=>monthStart.AddMonths(i-5)).ToArray();var monthly=months.Select(m=>new{Month=m,Count=rows.Count(r=>r.ReportDate.Year==m.Year&&r.ReportDate.Month==m.Month)}).ToList();var maxMonthly=Math.Max(1,monthly.Max(x=>x.Count));foreach(var x in monthly)MonthlyAnalytics.Add(new AnalyticsItem(x.Month.ToString("MMM yyyy"),x.Count,x.Count*100.0/maxMonthly));BuildGrouped(TypeAnalytics,rows.Where(r=>!string.IsNullOrWhiteSpace(r.ReportType)).GroupBy(r=>r.ReportType,StringComparer.OrdinalIgnoreCase).Select(g=>(g.Key,g.Count())).OrderByDescending(x=>x.Item2).Take(5));BuildGrouped(ChapterAnalytics,rows.Where(r=>!string.IsNullOrWhiteSpace(r.ChapterName)).GroupBy(r=>r.ChapterName,StringComparer.OrdinalIgnoreCase).Select(g=>(g.Key,g.Count())).OrderByDescending(x=>x.Item2).Take(5));}
 private static void BuildGrouped(ObservableCollection<AnalyticsItem> target,IEnumerable<(string Label,int Count)> values){target.Clear();var list=values.ToList();var max=Math.Max(1,list.Count==0?1:list.Max(x=>x.Count));foreach(var x in list)target.Add(new AnalyticsItem(x.Label,x.Count,x.Count*100.0/max));}
 private void Add(){if(new ReportEditorWindow{Owner=Owner}.ShowDialog()==true)Refresh();}private void Edit(){if(SelectedReport==null)return;if(new ReportEditorWindow(SelectedReport.ReportID){Owner=Owner}.ShowDialog()==true)Refresh();}
 private void Delete(){if(SelectedReport==null)return;if(MessageBox.Show(Owner,$"Delete report '{SelectedReport.Title}'?","Confirm delete",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;try{_repo.Delete(SelectedReport.ReportID);Load();}catch(Exception ex){MessageBox.Show(Owner,ex.Message,"Unable to delete report",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Export(){try{if(!ActivityReportPdfExporter.IsPdfPrinterAvailable())throw new InvalidOperationException("Microsoft Print to PDF is not available on this Windows installation.");var dlg=new SaveFileDialog{Filter="PDF files (*.pdf)|*.pdf",DefaultExt=".pdf",FileName=$"MFCYouth-ActivityReports-{DateTime.Now:yyyyMMdd-HHmm}.pdf"};if(dlg.ShowDialog(Owner)!=true)return;var context=new ActivityReportPdfExportContext(SearchText,SelectedChapter?.DisplayName??"All Chapters",SelectedReportType??"All Report Types",DateFrom.HasValue||DateTo.HasValue?$"{DateFrom:yyyy-MM-dd} to {DateTo:yyyy-MM-dd}":"All Dates",DateTime.Now);ActivityReportPdfExporter.Export(dlg.FileName,Reports.ToList(),context);MessageBox.Show(Owner,"PDF export completed.","Activity Reports",MessageBoxButton.OK,MessageBoxImage.Information);}catch(Exception ex){MessageBox.Show(Owner,ex.Message,"Unable to export PDF",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Refresh(){LoadFilters();Load();}private void ClearFilters(){SearchText="";SelectedChapter=ChapterOptions.FirstOrDefault();SelectedReportType="All Report Types";DateFrom=null;DateTo=null;Load();}
 public sealed record ChapterOption(string DisplayName,long? ChapterId,string? HistoricalName); public sealed record AnalyticsItem(string Label,int Count,double Percentage);
}
