using System.Globalization;using System.Windows;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.Utilities;
namespace MFCYouthAreaManagementSystem.Views.Dialogs;
public partial class EventEditorWindow:Window
{
 private readonly long? _id;private readonly EventRepository _repo=new();public long SavedEventId{get;private set;}
 public EventEditorWindow(long? id=null){InitializeComponent();_id=id;DatePicker.SelectedDate=DateTime.Today;TimeBox.Text="19:00";Heading.Text=id.HasValue?"Edit Event":"Add Event";Title=Heading.Text;if(id.HasValue)Load(id.Value);}
 private void Load(long id){var e=_repo.GetById(id)??throw new InvalidOperationException("Event not found.");NameBox.Text=e.EventName;DescriptionBox.Text=e.EventDescription;VenueBox.Text=e.Venue;DatePicker.SelectedDate=e.EventDateTime.Date;TimeBox.Text=e.EventDateTime.ToString("HH:mm");FeeBox.Text=e.RegistrationFee?.ToString("0.00")??"";PeopleBox.Text=e.PeopleAttended.ToString();}
 private void Save_Click(object s,RoutedEventArgs e){try{if(!DatePicker.SelectedDate.HasValue)throw new InvalidOperationException("Event Date is required.");if(!TimeSpan.TryParseExact(TimeBox.Text.Trim(),new[]{"h\\:mm","hh\\:mm"},CultureInfo.InvariantCulture,out var time))throw new InvalidOperationException("Enter time as HH:mm, for example 19:00.");decimal? fee=null;if(!string.IsNullOrWhiteSpace(FeeBox.Text)){if(!ValidationHelper.TryParsePositiveAmount(FeeBox.Text,out var f))throw new InvalidOperationException("Registration Fee must be greater than zero.");fee=f;}if(!int.TryParse(PeopleBox.Text.Trim(),out var people)||people<0)throw new InvalidOperationException("People Attended must be zero or greater.");var ev=new AreaEvent{EventID=_id??0,EventName=NameBox.Text.Trim(),EventDescription=DescriptionBox.Text.Trim(),Venue=VenueBox.Text.Trim(),EventDateTime=DatePicker.SelectedDate.Value.Date.Add(time),RegistrationFee=fee,PeopleAttended=people};if(_id.HasValue){_repo.Update(ev);SavedEventId=_id.Value;}else SavedEventId=_repo.Add(ev);DialogResult=true;}catch(Exception ex){MessageBox.Show(this,ex.Message,"Unable to save event",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
}
