using System.Windows;using System.Windows.Controls;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.Utilities;
namespace MFCYouthAreaManagementSystem.Views.Dialogs;
public partial class ParticipantEditorWindow:Window
{
 private readonly long _eventId;private readonly long? _id;private readonly EventParticipantRepository _repo=new();
 public ParticipantEditorWindow(long eventId,long? participantId=null){InitializeComponent();_eventId=eventId;_id=participantId;ChapterCombo.ItemsSource=new ChapterRepository().GetAll();ServiceCombo.ItemsSource=new ServiceRepository().GetAll();StatusCombo.ItemsSource=ApplicationConstants.PaymentStatuses;ModeCombo.ItemsSource=ApplicationConstants.PaymentModes;StatusCombo.SelectedItem="Not Paid";Heading.Text=participantId.HasValue?"Edit Participant":"Register Participant";Title=Heading.Text;if(participantId.HasValue)Load(participantId.Value);UpdatePaymentMode();}
 private void Load(long id){var p=_repo.GetById(id)??throw new InvalidOperationException("Participant not found.");FirstBox.Text=p.FirstName;MiddleBox.Text=p.MiddleInitial??"";LastBox.Text=p.LastName;AgeBox.Text=p.Age.ToString();ContactBox.Text=p.ContactNumber;AddressBox.Text=p.Address;ChapterCombo.SelectedItem=((IEnumerable<Chapter>)ChapterCombo.ItemsSource).FirstOrDefault(x=>x.ChapterID==p.ChapterID);ServiceCombo.SelectedItem=((IEnumerable<Service>)ServiceCombo.ItemsSource).FirstOrDefault(x=>x.ServiceID==p.ServiceID);StatusCombo.SelectedItem=p.PaymentStatus;AttendedCheck.IsChecked=p.Attended;if(!string.IsNullOrWhiteSpace(p.ModeOfPayment)&&!ApplicationConstants.PaymentModes.Contains(p.ModeOfPayment)){var list=ApplicationConstants.PaymentModes.ToList();list.Add(p.ModeOfPayment);ModeCombo.ItemsSource=list;}ModeCombo.SelectedItem=p.ModeOfPayment;}
 private void StatusCombo_SelectionChanged(object s,SelectionChangedEventArgs e)=>UpdatePaymentMode();private void UpdatePaymentMode(){if(ModeCombo==null)return;var paid=string.Equals(Convert.ToString(StatusCombo.SelectedItem),"Paid",StringComparison.OrdinalIgnoreCase);ModeCombo.IsEnabled=paid;if(!paid)ModeCombo.SelectedItem=null;}
 private void Save_Click(object s,RoutedEventArgs e){try{if(!int.TryParse(AgeBox.Text.Trim(),out var age))throw new InvalidOperationException("Enter a valid Age.");var chapter=ChapterCombo.SelectedItem as Chapter??throw new InvalidOperationException("Select a Chapter.");var service=ServiceCombo.SelectedItem as Service??throw new InvalidOperationException("Select a Service.");var p=new EventParticipant{ParticipantID=_id??0,EventID=_eventId,FirstName=FirstBox.Text.Trim(),MiddleInitial=string.IsNullOrWhiteSpace(MiddleBox.Text)?null:MiddleBox.Text.Trim(),LastName=LastBox.Text.Trim(),Age=age,ContactNumber=ContactBox.Text.Trim(),Address=AddressBox.Text.Trim(),ChapterID=chapter.ChapterID,ServiceID=service.ServiceID,PaymentStatus=Convert.ToString(StatusCombo.SelectedItem)??"Not Paid",ModeOfPayment=Convert.ToString(ModeCombo.SelectedItem),Attended=AttendedCheck.IsChecked==true};if(_id.HasValue)_repo.Update(p);else _repo.Add(p);DialogResult=true;}catch(Exception ex){MessageBox.Show(this,ex.Message,"Unable to save participant",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
}
