using System.Windows;using MFCYouthAreaManagementSystem.Models;using MFCYouthAreaManagementSystem.Repositories;using MFCYouthAreaManagementSystem.Utilities;
namespace MFCYouthAreaManagementSystem.Views.Dialogs;
public partial class ReportEditorWindow:Window
{
 private readonly long? _id;private readonly ActivityReportRepository _repo=new();private string _existingEventName="";
 public ReportEditorWindow(long? id=null){InitializeComponent();_id=id;ChapterCombo.ItemsSource=new ChapterRepository().GetAll();TypeCombo.ItemsSource=ApplicationConstants.ReportTypes;DatePicker.SelectedDate=DateTime.Today;var events=new List<EventChoice>{new(null,"None")};events.AddRange(new EventRepository().GetAll().Select(e=>new EventChoice(e.EventID,e.EventName)));EventCombo.ItemsSource=events;EventCombo.SelectedIndex=0;Heading.Text=id.HasValue?"Edit Activity Report":"Add Activity Report";Title=Heading.Text;if(id.HasValue)Load(id.Value);}
 private void Load(long id){var r=_repo.GetById(id)??throw new InvalidOperationException("Activity Report not found.");TitleBox.Text=r.Title;ChapterCombo.SelectedItem=((IEnumerable<Chapter>)ChapterCombo.ItemsSource).FirstOrDefault(c=>c.ChapterID==r.ChapterID);TypeCombo.SelectedItem=r.ReportType;DatePicker.SelectedDate=r.ReportDate;PreparedBox.Text=r.PreparedBy;ActivityBox.Text=r.Activity;DescriptionBox.Text=r.Description;_existingEventName=r.EventName;var ev=((IEnumerable<EventChoice>)EventCombo.ItemsSource).FirstOrDefault(x=>x.Id==r.EventID);if(ev!=null)EventCombo.SelectedItem=ev;}
 private void Save_Click(object s,RoutedEventArgs e){try{var chapter=ChapterCombo.SelectedItem as Chapter;if(!_id.HasValue&&chapter==null)throw new InvalidOperationException("Select a Chapter.");var ev=EventCombo.SelectedItem as EventChoice;var r=new ActivityReport{ReportID=_id??0,Title=TitleBox.Text.Trim(),ChapterID=chapter?.ChapterID,ChapterName=chapter?.ChapterName??"",EventID=ev?.Id,EventName=ev?.Id.HasValue==true?ev.Name:_existingEventName,ReportType=Convert.ToString(TypeCombo.SelectedItem)??"",Activity=ActivityBox.Text.Trim(),ReportDate=DatePicker.SelectedDate??default,PreparedBy=PreparedBox.Text.Trim(),Description=DescriptionBox.Text.Trim()};if(_id.HasValue)_repo.Update(r);else _repo.Add(r);DialogResult=true;}catch(Exception ex){MessageBox.Show(this,ex.Message,"Unable to save report",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 private void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
 public sealed record EventChoice(long? Id,string Name);
}
